### ISSUE TITLE
MSMBuilder 3

### ISSUE THREAD

**Issue by schwancr** [msmbuilder/msmbuilder-legacy#204]
Let's make a more concrete list of what we need to do before releasing MSMBuilder 3.

Concrete Items:
1. mdtraj - Replace Trajectory.py with new stuff in mdtraj
2. vectorizer - (in mdtraj) replace metrics with vectorizer classes
3. project handling - build an MSM from xtc/dcd/etc. as opposed to converting to hdf5 first
4. assignments file - rework without the -1 fillers
5. tica / kdml - pull these into msmbuilder as wrappers around a vectorizer
6. scripts - called under a single executable (```msmb cluster ...```)
   - include ability to print paper to cite (for instance when someone uses BACE)

Items needing more thought:
1. error analysis - bootstrap for now, until we have a better idea
2. streaming/online algorithms (birch)?
3. integration with OpenMM - examples and code for setting up a simulation (more of an mdtraj issue but still important)

**Comment by mpharrigan** [comment]
msmb3 was released a while ago
