### ISSUE TITLE
add msmbuilder-legacy docs to msmbuilder.org

### ISSUE THREAD

**Issue by schwancr** [msmbuilder/msmbuilder-legacy#453]
I think it should be possible to get msmbuilder.org/legacy to point to the msmbuilder-legacy docs, but I'm not sure what the right way to do it is. @rmcgibbo Do you have an idea? I'm worried that by updating the docs from the legacy code, it will overwrite the template stuff from the actual msmbuillder. So how can I only update the html files in msmbuilder.org/legacy?

**Comment by mpharrigan** [comment]
This was done
