### ISSUE TITLE
Conda / Simultaneous MSM2/3 install?

### ISSUE THREAD

**Issue by kyleabeauchamp** [msmbuilder/msmbuilder-legacy#455]
Need to figure out a couple of things:

1.  For omnia, which version(s) of MSMBuilder are going to come with the early january release.
2.  Do we need the ability to have both msmbuilder2 and msmbuilder3 installed in the same python environment?  If so, how to achieve this?  For example, we could find-replace msmbuilder with msmb2 and make a new release, but that seems hacky.
3.  If we don't need msmb2 and msmb3 in the same environment, we at least need to provide some clear instructions on how to do the conda installs / environment switching.

**Comment by mpharrigan** [comment]
I think we decided not to support this. Users should just use msmb3
